const routes = [
  /* {
    path: '/asis',
    meta: { menu: 'auth' },
    component: () => import('layouts/asis.vue')
  }, */
  {
    path: '/man',
    meta: { menu: 'MAN' },
    component: () => import('layouts/MyLayout.vue'),
    children: [
      { path: 'PR', component: () => import('pages/PR.vue'), name: 'PRad' },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'dtPembelian', component: () => import('pages/dtPembelian.vue') },
      { path: 'penjualan', component: () => import('pages/penjualan.vue') },
      { path: 'ASI', component: () => import('pages/dashboard.vue') },
      { path: 'salesReport', component: () => import('pages/sales/salesReport.vue') },
      { path: 'kasSales', component: () => import('pages/sales/KasSalesAll.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'stokall', component: () => import('pages/stokall.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'BoM', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: 'bukuExpedisi', component: () => import('pages/admin/bukuExpedisi.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'setting/cabang', component: () => import('pages/setting/dtCabang.vue') },
      { path: 'setting/produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'setting/partner', component: () => import('pages/partner.vue') },
      { path: 'setting/user', component: () => import('pages/setting/user.vue') },
      { path: 'setting/stokAwal', component: () => import('pages/setting/StokAwal.vue') },
      { path: 'setting/custCat', component: () => import('pages/setting/custCat.vue') },
      { path: 'acc', component: () => import('pages/acc/trxTunggu.vue') },
      { path: 'acc/jurnal', component: () => import('pages/jurnal.vue') },
      { path: 'acc/kas', component: () => import('pages/acc/Kas.vue') },
      { path: 'acc/kasMasuk', component: () => import('pages/acc/KasMasuk.vue') },
      { path: 'acc/bukubesar', component: () => import('pages/acc/bukuBesar.vue') },
      { path: 'acc/neraca', component: () => import('pages/acc/neraca.vue') },
      { path: 'acc/rugilaba', component: () => import('pages/acc/rugiLaba.vue') },
      { path: 'acc/neracasaldo', component: () => import('pages/acc/neracaSaldo.vue') },
      { path: 'acc/jurnalumum', component: () => import('pages/acc/jurnalUmum.vue') },
      { path: 'acc/hutang', component: () => import('pages/acc/hutang.vue') },
      { path: 'acc/piutang', component: () => import('pages/acc/piutang.vue') },
      { path: 'acc/akuncoa', component: () => import('pages/acc/akunCOA.vue') },
      { path: 'acc/aruskas', component: () => import('pages/acc/arusKas.vue') },
      { path: 'acc/partner', component: () => import('pages/partner.vue') },
      { path: 'acc/kasbon', component: () => import('pages/acc/Kasbon.vue') },
      { path: 'acc/mutasikas', component: () => import('pages/acc/MutasiKas.vue') },
      { path: 'acc/uploadHP', component: () => import('pages/acc/uploadHP.vue') },
      { path: 'piutangSales', component: () => import('pages/sales/piutangSales.vue') },
      { path: 'klaimPoint', component: () => import('pages/sales/klaimPoint.vue') },
      { path: 'pricing', component: () => import('pages/pricing.vue') },
      { path: 'kongsi', component: () => import('pages/kongsi.vue') },
      { path: 'faa', component: () => import('pages/dashboardFAA.vue') },
      { path: 'reportBeli', component: () => import('pages/reportPembelian.vue') },
      { path: '', component: () => import('pages/dashboardInvestor.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') }
    ]
  },
  {
    path: '/purchase',
    meta: { menu: 'purchase' },
    component: () => import('layouts/Purchase.vue'),
    children: [
      { path: 'PR', component: () => import('pages/PR.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'dtPembelian', component: () => import('pages/dtPembelian.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'penjualan', component: () => import('pages/penjualan.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') },
      { path: 'produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'stokall', component: () => import('pages/stokall.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'BoM', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: 'pricing', component: () => import('pages/pricing.vue') },
      { path: 'kongsi', component: () => import('pages/kongsi.vue') },
      { path: 'reportBeli', component: () => import('pages/reportPembelian.vue') },
      { path: 'setting/produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'setting/partner', component: () => import('pages/partner.vue') },
      { path: 'hutang', component: () => import('pages/acc/hutang.vue') },
      { path: 'piutang', component: () => import('pages/acc/piutang.vue') },
      { path: 'faa', component: () => import('pages/dashboardFAA.vue') },
      { path: '', component: () => import('pages/dashboard.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') }
    ]
  },
  {
    path: '/',
    meta: { menu: 'umum' },
    component: () => import('layouts/layoutAuth.vue'),
    children: [
      { path: '', component: () => import('pages/login.vue'), name: 'login' }
    ]
  },
  {
    path: '/login',
    meta: { menu: 'umum' },
    component: () => import('layouts/layoutAuth.vue'),
    children: [
      { path: '', component: () => import('pages/login.vue') }
    ]
  },
  {
    path: '/mitra',
    meta: { menu: 'mitra' },
    component: () => import('layouts/Mitra.vue'),
    children: [
      { path: '', component: () => import('pages/dashboard.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') },
      { path: 'KasSales', component: () => import('pages/sales/KasSalesAll.vue') },
      { path: 'PR', component: () => import('pages/PR.vue') },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'penjualan', component: () => import('pages/penjualan.vue') },
      { path: 'salesReport', component: () => import('pages/sales/salesReport.vue') },
      { path: 'dtPembelian', component: () => import('pages/dtPembelian.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') },
      { path: 'setting/produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'BoM', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'hutang', component: () => import('pages/admin/hutang.vue') },
      { path: 'piutang', component: () => import('pages/admin/piutang.vue') },
      { path: 'bukuExpedisi', component: () => import('pages/admin/bukuExpedisi.vue') },
      { path: 'trxTunggu', component: () => import('pages/acc/trxTunggu.vue') },
      { path: 'jurnal', component: () => import('pages/jurnal.vue') },
      { path: 'kas', component: () => import('pages/acc/Kas.vue') },
      { path: 'kasMasuk', component: () => import('pages/acc/KasMasuk.vue') },
      { path: 'bukubesar', component: () => import('pages/acc/bukuBesar.vue') },
      { path: 'neraca', component: () => import('pages/acc/neraca.vue') },
      { path: 'rugilaba', component: () => import('pages/acc/rugiLaba.vue') },
      { path: 'neracasaldo', component: () => import('pages/acc/neracaSaldo.vue') },
      { path: 'jurnalumum', component: () => import('pages/acc/jurnalUmum.vue') },
      { path: 'hutang', component: () => import('pages/acc/hutang.vue') },
      { path: 'piutang', component: () => import('pages/acc/piutang.vue') },
      { path: 'aruskas', component: () => import('pages/acc/arusKas.vue') },
      { path: 'dataKas', component: () => import('pages/acc/dataKas.vue') },
      { path: 'akuncoa', component: () => import('pages/acc/akunCOA.vue') },
      { path: 'kasbon', component: () => import('pages/acc/Kasbon.vue') },
      { path: 'mutasikas', component: () => import('pages/acc/MutasiKas.vue') },
      { path: 'deposit', component: () => import('pages/deposit.vue') },
      { path: 'uploadHP', component: () => import('pages/acc/uploadHP.vue') },
      { path: 'stokAwal', component: () => import('pages/setting/StokAwal.vue') },
      { path: 'piutangSales', component: () => import('pages/sales/piutangSales.vue') },
      { path: 'servis', component: () => import('pages/servis.vue') },
      { path: 'servisDone', component: () => import('pages/servisDone.vue') },
      { path: 'project', component: () => import('pages/project.vue') },
      { path: 'reportMRP', component: () => import('pages/reportMRP.vue') },
      { path: 'reportBeli', component: () => import('pages/reportPembelian.vue') },
      { path: 'reportPenjualan', component: () => import('pages/reportPenjualan.vue') },
      { path: 'faa', component: () => import('pages/dashboardFAA.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') },
      { path: 'dtPenjualanSN', component: () => import('pages/dtPenjualanSN.vue') }
    ]
  },
  {
    path: '/produksi',
    meta: { menu: 'produksi' },
    component: () => import('layouts/produksi.vue'),
    children: [
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: '', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'PR', component: () => import('pages/PR.vue') }
    ]
  },
  {
    path: '/gudang',
    meta: { menu: 'gudang' },
    component: () => import('layouts/gudang.vue'),
    children: [
      { path: 'PR', component: () => import('pages/PR.vue') },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'dataPO', component: () => import('pages/admin/PO.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: '', component: () => import('pages/sales/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'dtPembelian', component: () => import('pages/sales/dtPembelian.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'dtPenjualanSN', component: () => import('pages/dtPenjualanSN.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'BoM', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') }
    ]
  },
  {
    path: '/admin',
    meta: { menu: 'admin' },
    component: () => import('layouts/Admin.vue'),
    children: [
      { path: '', component: () => import('pages/dashboard.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') },
      { path: 'KasSales', component: () => import('pages/sales/KasSalesAll.vue'), name: 'KasSalesAll' },
      { path: 'PR', component: () => import('pages/PR.vue'), name: 'PR' },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'penjualan', component: () => import('pages/penjualan.vue'), name: 'penjualan' },
      { path: 'salesReport', component: () => import('pages/sales/salesReport.vue'), name: 'salesReport' },
      { path: 'dtPembelian', component: () => import('pages/sales/dtPembelian.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'produk', component: () => import('pages/produk.vue'), name: 'produk' },
      { path: 'stok', component: () => import('pages/stok.vue'), name: 'stok' },
      { path: 'stokall', component: () => import('pages/stokall.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue'), name: 'umurstok' },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue'), name: 'mutasi' },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: 'bukuExpedisi', component: () => import('pages/admin/bukuExpedisi.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') },
      { path: 'produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'kas', component: () => import('pages/acc/Kas.vue') },
      { path: 'kasMasuk', component: () => import('pages/acc/KasMasuk.vue') },
      { path: 'hutang', component: () => import('pages/admin/hutang.vue'), name: 'hutangA' },
      { path: 'piutang', component: () => import('pages/admin/piutang.vue'), name: 'piutangA' },
      { path: 'trxTunggu', component: () => import('pages/acc/trxTunggu.vue') },
      { path: '', component: () => import('pages/login.vue') },
      { path: 'mutasikas', component: () => import('pages/acc/MutasiKas.vue') },
      { path: 'piutangSales', component: () => import('pages/sales/piutangSales.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'bukubesar', component: () => import('pages/acc/bukuBesar.vue') },
      { path: 'pricing', component: () => import('pages/pricing.vue') },
      { path: 'servis', component: () => import('pages/servis.vue') },
      { path: 'servisDone', component: () => import('pages/servisDone.vue') },
      { path: 'kongsi', component: () => import('pages/kongsi.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') }
    ]
  },

  {
    path: '/sales',
    meta: { menu: 'sales' },
    component: () => import('layouts/Sales.vue'),
    children: [
      { path: '', component: () => import('pages/sales/retail.vue'), name: 'salesorder' },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'kassales', component: () => import('pages/sales/KasSales.vue'), name: 'kassales' },
      { path: 'performa', component: () => import('pages/sales/salesReport.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'piutang', component: () => import('pages/sales/piutangSales.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'partner', component: () => import('pages/sales/partner.vue') },
      { path: 'pricing', component: () => import('pages/pricing.vue') },
      { path: 'servis', component: () => import('pages/servis.vue') },
      { path: 'servisDone', component: () => import('pages/servisDone.vue') },
      { path: 'kongsi', component: () => import('pages/kongsi.vue') }
    ]
  },

  // akunting
  {
    path: '/acc',
    meta: { menu: 'acc' },
    component: () => import('layouts/Akunting.vue'),
    children: [
      { path: 'trxTunggu', component: () => import('pages/acc/trxTunggu.vue'), name: 'trxTunggu' },
      { path: '', component: () => import('pages/dashboard.vue') },
      { path: 'jurnal', component: () => import('pages/jurnal.vue'), name: 'jurnal' },
      { path: 'kas', component: () => import('pages/acc/Kas.vue') },
      { path: 'kasMasuk', component: () => import('pages/acc/KasMasuk.vue') },
      { path: 'bukubesar', component: () => import('pages/acc/bukuBesar.vue'), name: 'bukuBesar' },
      { path: 'neraca', component: () => import('pages/acc/neraca.vue'), name: 'neracaA' },
      { path: 'rugilaba', component: () => import('pages/acc/rugiLaba.vue'), name: 'rugiLaba' },
      { path: 'neracasaldo', component: () => import('pages/acc/neracaSaldo.vue') },
      { path: 'jurnalumum', component: () => import('pages/acc/jurnalUmum.vue'), name: 'jurnalUmum' },
      { path: 'bukuExpedisi', component: () => import('pages/admin/bukuExpedisi.vue') },
      { path: 'hutang', component: () => import('pages/acc/hutang.vue'), name: 'hutang' },
      { path: 'piutang', component: () => import('pages/acc/piutang.vue'), name: 'piutang' },
      { path: 'akuncoa', component: () => import('pages/acc/akunCOA.vue'), name: 'akunCOA' },
      { path: 'aruskas', component: () => import('pages/acc/arusKas.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') },
      { path: 'kasbon', component: () => import('pages/acc/Kasbon.vue') },
      { path: 'mutasikas', component: () => import('pages/acc/MutasiKas.vue') },
      { path: 'piutangSales', component: () => import('pages/sales/piutangSales.vue') },
      { path: 'PR', component: () => import('pages/PR.vue') },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'dtPembelian', component: () => import('pages/dtPembelian.vue') },
      { path: 'penjualan', component: () => import('pages/penjualan.vue') },
      { path: 'salesReport', component: () => import('pages/sales/salesReport.vue') },
      { path: 'kasSales', component: () => import('pages/sales/KasSalesAll.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'stokall', component: () => import('pages/stokall.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'BoM', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: 'bukuExpedisi', component: () => import('pages/admin/bukuExpedisi.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'setting/cabang', component: () => import('pages/setting/dtCabang.vue') },
      { path: 'setting/produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'setting/partner', component: () => import('pages/partner.vue') },
      { path: 'setting/user', component: () => import('pages/setting/user.vue') },
      { path: 'setting/uploadHP', component: () => import('pages/acc/uploadHP.vue') },
      { path: 'setting/stokAwal', component: () => import('pages/setting/StokAwal.vue') },
      { path: 'setting/uploadProduk', component: () => import('pages/setting/uploadProduk.vue') },
      { path: 'setting/custCat', component: () => import('pages/setting/custCat.vue') },
      { path: 'klaimPoint', component: () => import('pages/sales/klaimPoint.vue') },
      { path: 'pricing', component: () => import('pages/pricing.vue') },
      { path: 'deposit', component: () => import('pages/deposit.vue') },
      { path: 'kongsi', component: () => import('pages/kongsi.vue') },
      { path: 'servis', component: () => import('pages/servis.vue') },
      { path: 'servisDone', component: () => import('pages/servisDone.vue') },
      { path: 'faa', component: () => import('pages/dashboardFAA.vue') },
      { path: 'investor', component: () => import('pages/dashboardInvestor.vue') },
      { path: 'reportBeli', component: () => import('pages/reportPembelian.vue') },
      { path: 'reportPenjualan', component: () => import('pages/reportPenjualan.vue') },
      { path: 'project', component: () => import('pages/project.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') },
      { path: 'dtPenjualanSN', component: () => import('pages/dtPenjualanSN.vue') },
      { path: 'neracaBanding', component: () => import('pages/acc/neracaBanding.vue') },
      { path: 'rugilabaBanding', component: () => import('pages/acc/rugilabaBanding.vue') },
      { path: 'harian', component: () => import('pages/dashboardHarian.vue') }
      // { path: 'setting/chatRoom', component: () => import('pages/setting/videoConference.vue') }
    ]
  },
  {
    path: '/investor',
    meta: { menu: 'investor' },
    component: () => import('layouts/Investor.vue'),
    children: [
      { path: '', component: () => import('pages/dashboard.vue') },
      { path: 'bubes', component: () => import('pages/acc/bukuBesar.vue') },
      { path: 'neraca', component: () => import('pages/acc/neraca.vue') },
      { path: 'rugilaba', component: () => import('pages/acc/rugiLaba.vue') },
      { path: 'aruskas', component: () => import('pages/acc/arusKas.vue') }
    ]
  },
  {
    path: '/teknisi',
    meta: { menu: 'teknisi' },
    component: () => import('layouts/teknisi.vue'),
    children: [
      { path: '', component: () => import('pages/teknisi.vue') },
      { path: 'laporan', component: () => import('pages/teknisi.vue') },
      { path: 'rekap', component: () => import('pages/teknisi.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') }
    ]
  },
  {
    path: '/BMPrintex',
    meta: { menu: 'BMPrintex' },
    component: () => import('layouts/BMPrintex.vue'),
    children: [
      { path: '', component: () => import('pages/dashboard.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') },
      { path: 'KasSales', component: () => import('pages/sales/KasSalesAll.vue') },
      { path: 'PR', component: () => import('pages/PR.vue') },
      { path: 'dataPesanan', component: () => import('pages/pesanan.vue') },
      { path: 'rkpPesanan', component: () => import('pages/rekapPesanan.vue') },
      { path: 'dataPO', component: () => import('pages/PO.vue') },
      { path: 'penjualan', component: () => import('pages/penjualan.vue') },
      { path: 'salesReport', component: () => import('pages/sales/salesReport.vue') },
      { path: 'dtPembelian', component: () => import('pages/dtPembelian.vue') },
      { path: 'returPembelian', component: () => import('pages/sales/dtReturBeli.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'stokOpname', component: () => import('pages/stokOpname.vue') },
      { path: 'adjustment', component: () => import('pages/adjustment.vue') },
      { path: 'umurstok', component: () => import('pages/admin/umurStok.vue') },
      { path: 'mutasi', component: () => import('pages/admin/mutasi.vue') },
      { path: 'historyBarang', component: () => import('pages/admin/historyBarang.vue') },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'returPenjualan', component: () => import('pages/sales/dtReturJual.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') },
      { path: 'setting/produkCat', component: () => import('pages/setting/produkCat.vue') },
      { path: 'BoM', component: () => import('pages/produksi/BoM.vue') },
      { path: 'rakit', component: () => import('pages/produksi/rakit.vue') },
      { path: 'hutang', component: () => import('pages/admin/hutang.vue') },
      { path: 'piutang', component: () => import('pages/admin/piutang.vue') },
      { path: 'bukuExpedisi', component: () => import('pages/admin/bukuExpedisi.vue') },
      { path: 'trxTunggu', component: () => import('pages/acc/trxTunggu.vue') },
      { path: 'jurnal', component: () => import('pages/jurnal.vue') },
      { path: 'kas', component: () => import('pages/acc/Kas.vue') },
      { path: 'kasMasuk', component: () => import('pages/acc/KasMasuk.vue') },
      { path: 'bukubesar', component: () => import('pages/acc/bukuBesar.vue') },
      { path: 'neraca', component: () => import('pages/acc/neraca.vue') },
      { path: 'rugilaba', component: () => import('pages/acc/rugiLaba.vue') },
      { path: 'neracasaldo', component: () => import('pages/acc/neracaSaldo.vue') },
      { path: 'jurnalumum', component: () => import('pages/acc/jurnalUmum.vue') },
      { path: 'hutang', component: () => import('pages/acc/hutang.vue') },
      { path: 'piutang', component: () => import('pages/acc/piutang.vue') },
      { path: 'aruskas', component: () => import('pages/acc/arusKas.vue') },
      { path: 'dataKas', component: () => import('pages/acc/dataKas.vue') },
      { path: 'akuncoa', component: () => import('pages/acc/akunCOA.vue') },
      { path: 'kasbon', component: () => import('pages/acc/Kasbon.vue') },
      { path: 'mutasikas', component: () => import('pages/acc/MutasiKas.vue') },
      { path: 'deposit', component: () => import('pages/deposit.vue') },
      { path: 'uploadHP', component: () => import('pages/acc/uploadHP.vue') },
      { path: 'stokAwal', component: () => import('pages/setting/StokAwal.vue') },
      { path: 'piutangSales', component: () => import('pages/sales/piutangSales.vue') },
      { path: 'servis', component: () => import('pages/servis.vue') },
      { path: 'servisDone', component: () => import('pages/servisDone.vue') },
      { path: 'project', component: () => import('pages/project.vue') },
      { path: 'reportBeli', component: () => import('pages/reportPembelian.vue') },
      { path: 'reportPenjualan', component: () => import('pages/reportPenjualan.vue') },
      { path: 'faa', component: () => import('pages/dashboardFAA.vue') },
      { path: 'dashboardMarketing', component: () => import('pages/dashboardMarketing.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') },
      { path: 'dtPenjualanSN', component: () => import('pages/dtPenjualanSN.vue') }
    ]
  },
  {
    path: '/CS',
    meta: { menu: 'CS' },
    component: () => import('layouts/cs.vue'),
    children: [
      { path: '', component: () => import('pages/project.vue') },
      { path: 'mrp', component: () => import('pages/project.vue') },
      { path: 'piutang', component: () => import('pages/admin/piutang.vue'), name: 'piutangB' },
      { path: 'dtPenjualan', component: () => import('pages/dtPenjualan.vue') },
      { path: 'stok', component: () => import('pages/stok.vue') },
      { path: 'dashboardService', component: () => import('pages/dashboardService.vue') },
      { path: 'partner', component: () => import('pages/partner.vue') },
      { path: 'produk', component: () => import('pages/produk.vue') },
    ]
  },
  {
    path: '/operator',    
    component: () => import('layouts/operator.vue'),
    children: [
      { path: '', component: () => import('pages/operator.vue') }    
    ]
  },
]

// Always leave this as last one
if (process.env.MODE !== 'ssr') {
  routes.push({
    path: '*',
    component: () => import('pages/login.vue')
  })
}

export default routes
